defmodule GallformersWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :gallformers

  # The session is stored in the cookie, signed and encrypted.
  # secure: true is set in production only (dev/test use HTTP).
  @session_options [
    store: :cookie,
    key: "_gallformers_key",
    signing_salt: "Z2Zo8q/D",
    encryption_salt: "pP9YsGAhNA8=",
    same_site: "Lax",
    secure: Application.compile_env(:gallformers, :env) == :prod
  ]

  # log: :debug suppresses "CONNECTED TO Phoenix.LiveView.Socket" noise in prod logs
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], log: :debug],
    longpoll: [connect_info: [session: @session_options], log: :debug]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :gallformers,
    gzip: not code_reloading?,
    only: GallformersWeb.static_dirs(),
    only_matching: GallformersWeb.static_matching(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :gallformers
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Normalize Fly.io's fly-client-ip header into conn.remote_ip so downstream
  # consumers (LoggerJSON.Plug, rate limiting, etc.) see the real client IP.
  plug :put_client_ip

  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Rewrite host from X-Forwarded-Host header when behind CloudFront/proxy
  # This ensures OAuth callbacks use the correct host
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug GallformersWeb.Router

  # Fly.io sets fly-client-ip to the real client IP. Falls back to x-forwarded-for.
  defp put_client_ip(conn, _opts) do
    ip_string =
      case Plug.Conn.get_req_header(conn, "fly-client-ip") do
        [ip | _] when ip != "" ->
          ip |> String.split(",") |> List.first() |> String.trim()

        _ ->
          case Plug.Conn.get_req_header(conn, "x-forwarded-for") do
            [ips | _] -> ips |> String.split(",") |> List.first() |> String.trim()
            _ -> nil
          end
      end

    case ip_string && :inet.parse_address(String.to_charlist(ip_string)) do
      {:ok, parsed} -> %{conn | remote_ip: parsed}
      _ -> conn
    end
  end
end
