pipeline:
  name: bhl-deepinfra-ocr
  stages:
    - step: ocr
      model: deepinfra/allenai/olmOCR-2-7B-1025
    - step: preprocess
    - step: llm-clean
      model: deepinfra/Qwen/Qwen2.5-VL-32B-Instruct
    - step: metadata
      model: deepinfra/Qwen/Qwen2.5-VL-32B-Instruct
    - step: data-extract
      model: deepinfra/Qwen/Qwen2.5-VL-32B-Instruct
    - step: assemble
