name: CI
on: [push, pull_request]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install Yarn
              run: |
                  npm install -g yarn@4.7.0
                  yarn set version 4.7.0

            - name: Install dependencies
              run: yarn install --immutable

            - name: Generate Prisma Client
              run: yarn generate

            - name: Run database migrations
              run: yarn migrate

            - name: Run tests
              run: yarn test
              env:
                  CI: true

            - name: Upload test coverage
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage
                  path: .coverage/
                  retention-days: 7

            - name: Type Coverage
              run: yarn type-coverage
